# Use Azure ML OpenMPI base image
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

WORKDIR /app
# Root user should be changed after installation
USER root

# Install additional system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install PyTorch CPU and requirements
RUN pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir opencv-python-headless pillow scikit-learn tqdm

# Copy your project files
COPY . .